
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yobelchris
 */
public class ATMLain extends javax.swing.JFrame {
    
    Tarik tarik;

    /**
     * Creates new form ATMMain
     */
    public ATMLain(int saldo) {
        tarik = new Tarik(saldo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Sekolah (Gak mek tugas tok)\\Tekstur Blender\\Logo-Bank-Mega.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 0, 300, 230);

        jButton1.setText("Informasi Saldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 260, 180, 25);

        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 320, 180, 25);

        jButton3.setText("Penarikan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 380, 180, 25);

        jButton4.setText("Isi Pulsa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(400, 260, 180, 25);

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(400, 320, 180, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 540);

        setBounds(0, 0, 614, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Jumlah saldo anda = "+tarik.getSaldo(), "", 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pesan = JOptionPane.showInputDialog(null,"Masukkan nomor rekening","Transfer",3);
        
        try{
            int choice = Integer.parseInt(pesan);
            pesan = JOptionPane.showInputDialog(null,"Masukkan jumlah yang ingin ditransfer","Transfer",3);
            choice = Integer.parseInt(pesan);
            if(tarik.penarikan(choice)){
                JOptionPane.showMessageDialog(null, "Transfer Berhasil", "Transfer", 1);
                int input = JOptionPane.showOptionDialog(null, "Apa anda ingin melanjutkan transaksi?", "Transfer", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Silahkan ambil kartu anda", "Transfer", 1);
                    System.exit(0);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Transfer gagal", "Perhatian", 0);
            }
        }catch(NumberFormatException e) {
            if(e.toString().toLowerCase().indexOf("null".toLowerCase()) == -1){
                JOptionPane.showMessageDialog(null, "Anda harus memasukkan angka", "Perhatian", 0);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String pesan = JOptionPane.showInputDialog(null,"Masukkan jumlah yang ingin diambil","Transfer",3);
        
        try{
            int choice = Integer.parseInt(pesan);
            if(tarik.penarikan(choice)){
                JOptionPane.showMessageDialog(null, "Jumlah saldo = "+tarik.getSaldo(), "Berhasil", 1);
                int input = JOptionPane.showOptionDialog(null, "Apa anda ingin melanjutkan transaksi?", "Penarikan", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Silahkan ambil kartu anda", "Penarikan", 1);
                    System.exit(0);
                }
            }else{
                if(choice>50000){
                    JOptionPane.showMessageDialog(null, "Nominal harus lebih dari Rp50.000,00", "Perhatian", 0);
                }else{
                    JOptionPane.showMessageDialog(null, "Saldo tidak mencukupi", "Perhatian", 0);
                }
            }
        }catch(NumberFormatException e) {
            if(e.toString().toLowerCase().indexOf("null".toLowerCase()) == -1){
                JOptionPane.showMessageDialog(null, "Anda harus memasukkan angka", "Perhatian", 0);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String pesan = JOptionPane.showInputDialog(null,"Masukkan nomor telepon yang ingin diisi","Transfer",3);
        
        try{
            int choice = Integer.parseInt(pesan);
            pesan = JOptionPane.showInputDialog(null,"Masukkan jumlah pulsa","Transfer",3);
            choice = Integer.parseInt(pesan);
            if(tarik.penarikan(choice)){
                JOptionPane.showMessageDialog(null, "Transfer Berhasil", "Transfer", 1);
                int input = JOptionPane.showOptionDialog(null, "Apa anda ingin melanjutkan transaksi?", "Transfer", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Silahkan ambil kartu anda", "Transfer", 1);
                    System.exit(0);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Transfer gagal", "Perhatian", 0);
            }
        }catch(NumberFormatException e) {
            if(e.toString().toLowerCase().indexOf("null".toLowerCase()) == -1){
                JOptionPane.showMessageDialog(null, "Anda harus memasukkan angka", "Perhatian", 0);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ATMMain(tarik.getSaldo()).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
